[build-system]
requires = [
  "numpy",
  "Cython",
  "setuptools",
  "wheel",
]
[tool.black]
line_length = 80
exclude = '''
/(
    \.git
  | \.hg
  | \.mypy_cache
  | \.tox
  | \.venv
  | \.readme
  | _build
  | buck-out
  | build
  | dist
  | data
  | tools
  | scripts
)/
'''
